# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ianhuang/Desktop/Portfolio/Cyan/cyan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ianhuang/Desktop/Portfolio/Cyan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ianhuang/Desktop/Portfolio/Cyan/CMakeFiles /Users/ianhuang/Desktop/Portfolio/Cyan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ianhuang/Desktop/Portfolio/Cyan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cyantest

# Build rule for target.
cyantest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cyantest
.PHONY : cyantest

# fast build rule for target.
cyantest/fast:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/build
.PHONY : cyantest/fast

# target to build an object file
arithmetic.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/arithmetic.o
.PHONY : arithmetic.o

# target to preprocess a source file
arithmetic.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/arithmetic.i
.PHONY : arithmetic.i

# target to generate assembly for a file
arithmetic.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/arithmetic.s
.PHONY : arithmetic.s

# target to build an object file
cyarray.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyarray.o
.PHONY : cyarray.o

# target to preprocess a source file
cyarray.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyarray.i
.PHONY : cyarray.i

# target to generate assembly for a file
cyarray.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyarray.s
.PHONY : cyarray.s

# target to build an object file
cyio.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyio.o
.PHONY : cyio.o

# target to preprocess a source file
cyio.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyio.i
.PHONY : cyio.i

# target to generate assembly for a file
cyio.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyio.s
.PHONY : cyio.s

# target to build an object file
cyobject.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyobject.o
.PHONY : cyobject.o

# target to preprocess a source file
cyobject.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyobject.i
.PHONY : cyobject.i

# target to generate assembly for a file
cyobject.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cyobject.s
.PHONY : cyobject.s

# target to build an object file
cystring.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cystring.o
.PHONY : cystring.o

# target to preprocess a source file
cystring.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cystring.i
.PHONY : cystring.i

# target to generate assembly for a file
cystring.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/cystring.s
.PHONY : cystring.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/main.s
.PHONY : main.s

# target to build an object file
members.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/members.o
.PHONY : members.o

# target to preprocess a source file
members.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/members.i
.PHONY : members.i

# target to generate assembly for a file
members.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/members.s
.PHONY : members.s

# target to build an object file
primitive.o:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/primitive.o
.PHONY : primitive.o

# target to preprocess a source file
primitive.i:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/primitive.i
.PHONY : primitive.i

# target to generate assembly for a file
primitive.s:
	$(MAKE) -f CMakeFiles/cyantest.dir/build.make CMakeFiles/cyantest.dir/primitive.s
.PHONY : primitive.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cyantest"
	@echo "... arithmetic.o"
	@echo "... arithmetic.i"
	@echo "... arithmetic.s"
	@echo "... cyarray.o"
	@echo "... cyarray.i"
	@echo "... cyarray.s"
	@echo "... cyio.o"
	@echo "... cyio.i"
	@echo "... cyio.s"
	@echo "... cyobject.o"
	@echo "... cyobject.i"
	@echo "... cyobject.s"
	@echo "... cystring.o"
	@echo "... cystring.i"
	@echo "... cystring.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... members.o"
	@echo "... members.i"
	@echo "... members.s"
	@echo "... primitive.o"
	@echo "... primitive.i"
	@echo "... primitive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

